document.getElementById("lngtouch").innerHTML = 'Tap to record';
document.getElementById("lngoptions").innerHTML = 'Settings';
document.getElementById("lngaudio").innerHTML = 'Last conversion';
document.getElementById("lnglang").innerHTML = 'Switch language';
document.getElementById("offtitle").innerHTML = 'An internet connection is required.';
document.getElementById("offtext").innerHTML = 'Please , enable wifi or cellphone data and retry.';
document.getElementById("author").innerHTML = 'Author';
var duringrec = 'Recording...';
var postrec = 'Tap to record';